version: "3.8"

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus: {}
  grafana_data: {}

services:
  app:
    image: "periodum_api:${TAG}"
    container_name: periodum_api
    build:
      context: .
      args:
        - NODEJS_VERSION=${NODEJS_VERSION}
        - NODE_ENV=${NODE_ENV}
    volumes:
      - ./src:/usr/app/src
    ports:
      - "127.0.0.1:${NODEJS_PORT}:3000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - monitoring
  db:
    image: "mongo:${MONGO_DB_VERSION}"
    container_name: periodum_db
    volumes:
        - ./db/mongodb:/data/db
    restart: unless-stopped
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:8.2.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_HTTP_PORT=8080
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - monitoring
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    expose:
      - 9100
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      - monitoring
