# This is a basic workflow to help you get started with Actions

name: Periodum CI

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/periodum-dev

    steps:
      - uses: actions/checkout@v2

      - name: Install 3rd party libraries
        run: npm install

      - name: Install Development Dependencies
        run: npm install -D

      - name: Checking the syntax
        run: npm run lint

      - name: Create the DB
        run: npx prisma migrate deploy  

      - name: Run the tests
        run: npm test

      - name: Build
        run: npm run build
